## Regression Model in Keras

### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import keras 

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

### Reading Data

In [2]:
df = pd.read_csv('concrete_data.csv')
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

### X and Y Extraction

In [3]:
target = df['Strength'] # Strength column
predictors = df.iloc[:,:-1] # all columns except Strength

predictors

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360
...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28

## Normalization

In [11]:
predictors = (predictors - predictors.mean()) / predictors.std()
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

### Spliting to Train and Test

In [12]:
X_train , X_test , y_train , y_test = train_test_split(predictors , target , test_size=0.3 ,random_state=120)

print("X_train : " ,X_train.shape)
print("y_train : " ,y_train.shape)
print("X_Test : " ,X_test.shape)
print("y_test : " ,y_test.shape)

X_train :  (721, 8)
y_train :  (721,)
X_Test :  (309, 8)
y_test :  (309,)

### Creating Model

In [17]:
model = keras.models.Sequential([
    keras.layers.InputLayer(input_shape=(8,)),
    keras.layers.Dense(10,activation='relu'),
    keras.layers.Dense(10,activation='relu'),
    keras.layers.Dense(10,activation='relu'),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam' , loss='mean_squared_error' , metrics=['accuracy'])

### Model Training

In [18]:
model.fit(X_train , y_train , epochs=50)

Epoch 1/50
23/23 [==============================] - 1s 2ms/step - loss: 1581.3597 - accuracy: 0.0000e+00
Epoch 2/50
23/23 [==============================] - 0s 2ms/step - loss: 1569.0220 - accuracy: 0.0000e+00
Epoch 3/50
23/23 [==============================] - 0s 2ms/step - loss: 1560.5900 - accuracy: 0.0000e+00
Epoch 4/50
23/23 [==============================] - 0s 2ms/step - loss: 1552.3184 - accuracy: 0.0000e+00
Epoch 5/50
23/23 [==============================] - 0s 2ms/step - loss: 1541.4370 - accuracy: 0.0000e+00
Epoch 6/50
23/23 [==============================] - 0s 2ms/step - loss: 1524.8951 - accuracy: 0.0000e+00
Epoch 7/50
23/23 [==============================] - 0s 2ms/step - loss: 1498.3976 - accuracy: 0.0000e+00
Epoch 8/50
23/23 [==============================] - 0s 2ms/step - loss: 1458.1115 - accuracy: 0.0000e+00
Epoch 9/50
23/23 [==============================] - 0s 2ms/step - loss: 1402.0336 - accuracy: 0.0000e+00
Epoch 10/50
23/23 [==============================] - 0s 2ms/step - loss: 1327.0277 - accuracy: 0.0000e+00
Epoch 11/50
23/23 [==============================] - 0s 2ms/step - loss: 1228.6770 - accuracy: 0.0000e+00
Epoch 12/50
23/23 [==============================] - 0s 2ms/step - loss: 1110.1625 - accuracy: 0.0000e+00
Epoch 13/50
23/23 [==============================] - 0s 2ms/step - loss: 968.8884 - accuracy: 0.0000e+00
Epoch 14/50
23/23 [==============================] - 0s 2ms/step - loss: 813.2538 - accuracy: 0.0000e+00
Epoch 15/50
23/23 [==============================] - 0s 2ms/step - loss: 657.1906 - accuracy: 0.0000e+00
Epoch 16/50
23/23 [==============================] - 0s 2ms/step - loss: 516.9033 - accuracy: 0.0000e+00
Epoch 17/50
23/23 [==============================] - 0s 2ms/step - loss: 403.7921 - accuracy: 0.0000e+00
Epoch 18/50
23/23 [==============================] - 0s 2ms/step - loss: 324.8619 - accuracy: 0.0000e+00
Epoch 19/50
23/23 [==============================] - 0s 2ms/step - loss: 275.7758 - accuracy: 0.0000e+00
Epoch 20/50
23/23 [==============================] - 0s 2ms/step - loss: 245.3390 - accuracy: 0.0000e+00
Epoch 21/50
23/23 [==============================] - 0s 2ms/step - loss: 226.5650 - accuracy: 0.0000e+00
Epoch 22/50
23/23 [==============================] - 0s 2ms/step - loss: 212.2720 - accuracy: 0.0000e+00
Epoch 23/50
23/23 [==============================] - 0s 2ms/step - loss: 201.0923 - accuracy: 0.0000e+00
Epoch 24/50
23/23 [==============================] - 0s 2ms/step - loss: 192.1922 - accuracy: 0.0000e+00
Epoch 25/50
23/23 [==============================] - 0s 2ms/step - loss: 184.9411 - accuracy: 0.0000e+00
Epoch 26/50
23/23 [==============================] - 0s 2ms/step - loss: 178.8712 - accuracy: 0.0000e+00
Epoch 27/50
23/23 [==============================] - 0s 2ms/step - loss: 173.9900 - accuracy: 0.0000e+00
Epoch 28/50
23/23 [==============================] - 0s 2ms/step - loss: 169.9281 - accuracy: 0.0000e+00
Epoch 29/50
23/23 [==============================] - 0s 2ms/step - loss: 166.4684 - accuracy: 0.0000e+00
Epoch 30/50
23/23 [==============================] - 0s 2ms/step - loss: 163.0300 - accuracy: 0.0000e+00
Epoch 31/50
23/23 [==============================] - 0s 2ms/step - loss: 160.0467 - accuracy: 0.0000e+00
Epoch 32/50
23/23 [==============================] - 0s 2ms/step - loss: 157.5769 - accuracy: 0.0000e+00
Epoch 33/50
23/23 [==============================] - 0s 2ms/step - loss: 155.1698 - accuracy: 0.0000e+00
Epoch 34/50
23/23 [==============================] - 0s 2ms/step - loss: 152.8661 - accuracy: 0.0000e+00
Epoch 35/50
23/23 [==============================] - 0s 2ms/step - loss: 151.0077 - accuracy: 0.0000e+00
Epoch 36/50
23/23 [==============================] - 0s 2ms/step - loss: 149.1350 - accuracy: 0.0000e+00
Epoch 37/50
23/23 [==============================] - 0s 2ms/step - loss: 147.3897 - accuracy: 0.0000e+00
Epoch 38/50
23/23 [==============================] - 0s 2ms/step - loss: 145.5166 - accuracy: 0.0000e+00
Epoch 39/50
23/23 [==============================] - 0s 2ms/step - loss: 143.9681 - accuracy: 0.0000e+00
Epoch 40/50
23/23 [==============================] - 0s 2ms/step - loss: 142.6071 - accuracy: 0.0000e+00
Epoch 41/50
23/23 [==============================] - 0s 2ms/step - loss: 140.9197 - accuracy: 0.0000e+00
Epoch 42/50
23/23 [==============================] - 0s 2ms/step - loss: 139.6383 - accuracy: 0.0000e+00
Epoch 43/50
23/23 [==============================] - 0s 2ms/step - loss: 138.0459 - accuracy: 0.0000e+00
Epoch 44/50
23/23 [==============================] - 0s 2ms/step - loss: 136.9020 - accuracy: 0.0000e+00
Epoch 45/50
23/23 [==============================] - 0s 2ms/step - loss: 135.7720 - accuracy: 0.0000e+00
Epoch 46/50
23/23 [==============================] - 0s 2ms/step - loss: 134.4940 - accuracy: 0.0000e+00
Epoch 47/50
23/23 [==============================] - 0s 2ms/step - loss: 133.4571 - accuracy: 0.0000e+00
Epoch 48/50
23/23 [==============================] - 0s 2ms/step - loss: 132.2671 - accuracy: 0.0000e+00
Epoch 49/50
23/23 [==============================] - 0s 2ms/step - loss: 131.3444 - accuracy: 0.0000e+00
Epoch 50/50
23/23 [==============================] - 0s 2ms/step - loss: 130.3699 - accuracy: 0.0000e+00

### Evaluate the model

In [19]:
pred_test= model.predict(X_test)

mean_squared_err = mean_squared_error(y_test,pred_test)

mean = np.mean(mean_squared_err)
std_dev = np.std(mean_squared_err)

print("Mean : ", mean , " And Standard Deviation :", std_dev)

10/10 [==============================] - 0s 2ms/step
Mean :  138.879159705535  And Standard Deviation : 0.0

### create a list of 50 mean squared errors

In [20]:
epochs_number = 100
mean_sq_errs = []
number_of_reapeat = 50

for i in range(0,number_of_reapeat):
    X_train , X_test , y_train , y_test = train_test_split(predictors , target , test_size=0.3 ,random_state=i)
    model.fit(X_train , y_train , epochs=epochs_number , verbose=0)
    
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    
    y_pred= model.predict(X_test)
    mean_squared_err = mean_squared_error(y_test,y_pred)
    mean_sq_errs.append(mean_squared_err)


mean_sq_errs_arr = np.array(mean_sq_errs)
mean = np.mean(mean_sq_errs_arr)
std_dev = np.std(mean_sq_errs_arr)

print("Mean: "+ str(mean))
print("Standard Deviation: "+str(std_dev))

MSE 1: [59.4937744140625, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 2: [44.54098892211914, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 3: [32.42769241333008, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 4: [32.76741027832031, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 5: [35.90471267700195, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 6: [31.782087326049805, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 7: [32.923526763916016, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 8: [25.710708618164062, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 9: [31.058271408081055, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 10: [29.34568977355957, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 11: [25.761777877807617, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 12: [23.352340698242188, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 13: [29.641923904418945, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 14: [29.22451400756836, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 15: [24.215089797973633, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 16: [20.027515411376953, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 17: [26.041473388671875, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 18: [25.403362274169922, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 19: [21.942203521728516, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 20: [25.509092330932617, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 21: [25.965557098388672, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 22: [25.782001495361328, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 23: [20.055152893066406, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 24: [20.131887435913086, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 25: [25.482019424438477, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 26: [23.258865356445312, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 27: [21.450559616088867, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 28: [23.3397159576416, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 29: [25.02581024169922, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 30: [19.77435302734375, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 31: [17.734352111816406, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 32: [18.126283645629883, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 33: [17.912050247192383, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 34: [20.335983276367188, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 35: [21.883251190185547, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 36: [26.951801300048828, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 37: [19.065528869628906, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 38: [18.796480178833008, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 39: [24.650163650512695, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 40: [18.684709548950195, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 41: [22.919109344482422, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 42: [16.851757049560547, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 43: [18.757230758666992, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 44: [24.042043685913086, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 45: [21.957340240478516, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 46: [18.417770385742188, 0.0]
10/10 [==============================] - 0s 2ms/step
MSE 47: [17.38370132446289, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 48: [18.117355346679688, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 49: [18.283370971679688, 0.0]
10/10 [==============================] - 0s 1ms/step
MSE 50: [19.588346481323242, 0.0]
10/10 [==============================] - 0s 2ms/step
Mean: 24.755973861367433
Standard Deviation: 7.462874830117464